### ISSUE TITLE
Refactoring with futile.logger v1.5

### ISSUE THREAD

**Issue by spencerpease** [MazamaScience/MazamaCoreUtils#14]
# Description

Supposedly, the _futile.logger_ package version 1.5 should be released to CRAN sometime this year. This version (already available on GitHub) has a new _appender_ function `appender.file2` which sets up a python-style logging hierarchy similar to what we create now with `logger.setup` (ie, one log file for each logging level). 

Making use of the new functionality on _futile.logger_ could potentially eliminate the need to set up custom logging functions in _MazamaCoreUtils_. Instead, we would set up logging in a package's `.onLoad` function, and use _MazamaCoreUtils_ to instead pass a list of options that would define how the logger operates. This could be things like setting the log file directories for operational docker services versus local development, or whether or not to log to the console.

# References

[Blog post about futile.logger v1.5][1]
[Information about logging hierarchy in futile.logger][2]
[Issue about `appender.file2` not being on CRAN][3]

[1]: https://cartesianfaith.com/2018/12/15/request-for-comments-on-planned-features-for-futile-logger-1-5/
[2]: https://github.com/zatonovo/futile.logger#logging-hierarchy
[3]: https://github.com/zatonovo/futile.logger/issues/65

**Comment by jonathancallahan** [comment]
Three years later, version 1.5 has never been released.
