### ISSUE TITLE
potential issue with pas_leaflet

### ISSUE THREAD

**Issue by acollier-oxandale** [MazamaScience/MazamaCoreUtils#23]
When using pas_leaflet, the map seems to be displaying the concentration for the last hour regardless of which parameter is selected. In the two examples I have plotted the "pm25_current" and "pm25_1day" respectively and in both cases the label displays the 1 hour value (and the color may also be based on that 1 hour value). The pas data for the selected sensor is visible in the upper left of the screenshot and the top row is the A channel. (I most recently updated the package yesterday) thank you!

![example1](https://user-images.githubusercontent.com/48835544/62244700-d1543800-b394-11e9-9a6d-448f868ce3de.png)
![example2](https://user-images.githubusercontent.com/48835544/62244705-d44f2880-b394-11e9-83f9-a282d06c6f6d.png)

**Comment by hansmrtn** [comment]
Ashley, 
Thank you for using GitHub - and great catch! 
This is an error we have missed. Working on a fix now.

**Comment by hansmrtn** [comment]
Should be fixed now! Go ahead and update the Package using the Master branch. 

- Hans

**Comment by acollier-oxandale** [comment]
Awesome, thanks Hans!
