### ISSUE TITLE
Consider adding support for parsing of Julian dates

### ISSUE THREAD

**Issue by lagerratrobe** [MazamaScience/MazamaCoreUtils#33]
MazamaSatelliteUtils currently supports requests to download and/or list  files by day or hour as specified by the user.  The format of the input can either be a string or a time object that is either in YYYY-MM-DD-HH format, or in Julian date format (YYYYJJJHHMMSS).  For the standard datetime format, we use the parseDatetime() function in MazamaCoreUtils, but for Julian date we use a call to lubridate.

Given the similarity in how parseDatetime() uses lubridate already to parse datetime strings, I suggest that we extend its functionality to also parse Julian dates.

A standard datetime string might look something like this:
* 2019-09-06 16
or 
* 2019090616

A Julian Date string can look  like any of the following:
* 20192491651196 (Sep 6, 2019 16:51:19 6)
or
* 201924916 (Sep 6, 2019 16:00)
or even
* 2019249 (Sep 6, 2019)

Given the similarity that exists between the standard datetime string and some of the Julian date formats, it is important that the function is able to differentiate between both types. We don't want to break the standard parsing that it already does so well, so I propose that we add a silent parameter named "jdate" and set it to FALSE.

The function would be called in this fashion:

```MazamaCoreUtils::parseDatetime(startdate, timezone = "UTC", jdate = TRUE)```

The presence of the TRUE _jdate_ parameter would immediately pass the _startdate_ into a section of parseDatetime that  looks something like this:

```
    jorders <- c("Yj", "YjH", "YjHMS")
    parsedDatetime <- lubridate::parse_date_time(datetime, 
                                          orders = jorders, 
                                           tz = timezone, 
                                           quiet = quiet)
```

**Comment by jonathancallahan** [comment]
Thanks for the *excellent* issue post. This is now resolved in MazamaCoreUtils 0.3.9.

I was able to add support for julian date strings with fractional seconds as seen in the NASA GOES filenames.
